// src/components/About/About.jsx
import * as React from 'react';
import { Grid, Typography, Box } from "@mui/material";
import { motion } from "framer-motion";
import { FaDownload } from "react-icons/fa";
import myImage from "../../assets/images/headshotchathupa.png";
import cvFile from "../../assets/documents/ChathupaCV.pdf";

// Neon Border Animation Keyframes
const neonBorderKeyframes = `
  @keyframes neon-border {
    0% { background-position: 0% 50%; }
    50% { background-position: 100% 50%; }
    100% { background-position: 0% 50%; }
  }
`;

// Append keyframes to the document head
const style = document.createElement("style");
style.type = "text/css";
style.innerHTML = neonBorderKeyframes;
document.head.appendChild(style);

const About = () => {
  return (
    <Grid
      container
      id="home"
      alignItems="center"
      sx={{
        marginTop: "-50px",
        minHeight: "100vh",
        textAlign: { xs: "center", md: "left" },
        background: "transparent",
        color: "white",
        padding: { xs: "2rem", md: "0" },
      }}
    >
      {/* Profile Image */}
      <Grid
        item
        xs={12}
        md={6}
        sx={{
          display: "flex",
          justifyContent: "center",
          marginBottom: { xs: "2rem", md: "0" },
        }}
      >
        <motion.div
          initial={{ x: -50, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          transition={{ duration: 0.8, delay: 0.2 }}
        >
          <img
            src={myImage}
            alt="Chathupa Profile"
            style={{
              width: "80%",
              maxWidth: "300px",
              height: "auto",
              borderRadius: "50%",
              boxShadow: "0 0 20px rgba(128, 0, 255, 0.8)",
              border: "5px solid rgba(128, 0, 255, 0.8)",
              marginTop: "10px", // Adjust this for mobile responsiveness
            }}
          />
        </motion.div>
      </Grid>

      {/* Details Section */}
      <Grid item xs={12} md={6}>
        <motion.div
          initial={{ x: 50, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          transition={{ duration: 0.8, delay: 0.4 }}
        >
          <Typography
            component="h1"
            sx={{
              fontSize: { xs: "2rem", md: "3rem" },
              fontWeight: "bold",
              background: "linear-gradient(to right, #4facfe, #00f2fe)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
            }}
          >
            Chathupa Chamika
          </Typography>
          <Typography
            component="h2"
            sx={{
              fontSize: { xs: "1.2rem", md: "1.8rem" },
              fontWeight: "bold",
              background: "linear-gradient(to right, #f953c6, #b91d73)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
              marginTop: "0.5rem",
            }}
          >
            Full Stack Developer
          </Typography>
          <Typography
            sx={{
              fontSize: { xs: "0.9rem", md: "1rem" },
              color: "rgba(255, 255, 255, 0.8)",
              marginTop: "1.5rem",
            }}
          >
            An enthusiastic and dedicated university student with a strong
            foundation in frontend, backend, and full stack development. Skilled
            in software engineering and problem-solving, with a keen interest in
            leveraging IT expertise to develop innovative solutions. Seeking a
            free, volunteer-based software engineering internship to apply my
            technical skills and gain valuable industry experience while
            contributing to meaningful projects.
          </Typography>

          {/* Download CV Button */}
          <Box
            sx={{
              marginTop: "2rem",
              display: "flex",
              justifyContent: { xs: "center", md: "flex-start" },
            }}
          >
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 1, delay: 0.6 }}
              style={{
                position: "relative",
                display: "inline-block",
              }}
            >
              <a
                href={cvFile}
                download
                style={{
                  textDecoration: "none",
                }}
              >
                <Box
                  sx={{
                    position: "relative",
                    padding: "0.8rem 2rem",
                    fontSize: "1rem",
                    fontWeight: "bold",
                    color: "white",
                    textAlign: "center",
                    backgroundColor: "#0a0a23",
                    borderRadius: "30px",
                    overflow: "hidden",
                    cursor: "pointer",
                    zIndex: 1,
                    transition: "background-color 0.3s",
                    "&:hover": {
                      backgroundColor: "#1a1a33",
                    },
                    "&::before": {
                      content: '""',
                      position: "absolute",
                      inset: 0,
                      borderRadius: "30px",
                      padding: "2px",
                      background:
                        "linear-gradient(90deg, #ebdb34, #00f2fe, #4facfe, #ebdb34)",
                      mask: "linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)",
                      WebkitMask:
                        "linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)",
                      maskComposite: "exclude",
                      WebkitMaskComposite: "destination-out",
                      animation: "neon-border 2s linear infinite",
                      zIndex: -1,
                    },
                  }}
                >
                  <FaDownload style={{ marginRight: "8px" }} /> Download CV
                </Box>
              </a>
            </motion.div>
          </Box>
        </motion.div>
      </Grid>
    </Grid>
  );
};

export default About;

// src/app/about/about.component.ts
import { Component, OnInit } from '@angular/core';
import AOS from 'aos';
@Component({
  selector: 'app-about',
  standalone: true,
  imports: [],
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {
  ngOnInit() {
    AOS.init({
      duration: 1200, 
      once: true      
    });
  }
  downloadCV(): void {
    const cvPath = 'C:/ICD110/web%20developing/PortFolio-main/PortFolio-main/src/assets/cv/ATS%20CV%20Resume.pdf'; 
    const link = document.createElement('a');
    link.href = cvPath;
    link.download = 'ATS CV Resume.pdf';
    document.body.appendChild(link); 
    link.click(); 
    document.body.removeChild(link); 
  }
}

<div class="bg-gray-200 text-center p-10 rounded-lg shadow-lg">
    <div 
      alt="Profile Picture" 
      role="img"
      aria-label="Profile Picture"
      class="rounded-full mx-auto w-60 h-60 border-4 border-blue-500 shadow-md bg-cover bg-center image">
    </div>
    
    <h1 class="text-3xl font-extrabold mt-6 text-gray-800">Chathupa Chamika</h1>

    <!-- Apply animation to paragraphs -->
    <p class="neon-animation-text mt-4">
      Hello! I'm a passionate developer from Ambalangoda, Sri Lanka. I specialize in front-end, back-end,
      and full-stack development. Currently preparing for my university journey, I'm focused on delivering 
      innovative solutions with seamless user experiences.
    </p>

    <div class="mt-6 flex flex-wrap justify-center gap-6">
        <a href="https://github.com/Chathupachamika" 
           target="_blank" 
           class="neon-btn github-btn flex items-center justify-center">
          <i class="fab fa-github"></i> GitHub
        </a>
        <a href="https://linkedin.com/in/chathupa-chamika-" 
           target="_blank" 
           class="neon-btn linkedin-btn flex items-center justify-center">
          <i class="fab fa-linkedin"></i> LinkedIn
        </a>
        <a href="mailto:Chathupachamika765@gmail.com" 
           class="neon-btn email-btn flex items-center justify-center">
          <i class="fas fa-envelope"></i> Contact Me
        </a>
    </div>
    
    <!-- Download CV Section -->
    <div class="mt-10">
      <button 
        class="neon-btn px-6 py-2 rounded-lg font-semibold transition-all transform hover:scale-110 hover:bg-blue-600 bg-blue-500 text-white"
        (click)="downloadCV()">
        Download CV
      </button>
    </div>
    
    <div class="mt-10 text-gray-700 text-left max-w-2xl mx-auto">
      <h2 class="text-xl font-bold mb-4">About Me</h2>
      
      <!-- Apply animation to the second paragraph -->
      <p class="neon-animation-text">
        I am an enthusiastic university student and a certified developer from ICET, pursuing a diploma in software engineering. 
        My expertise lies in Java, JavaScript, and Spring Boot, and I have hands-on experience in building custom web and mobile applications. 
        I thrive in dynamic environments where I can apply my skills to create impactful and user-friendly solutions.
      </p>

      <p class="mt-4 neon-animation-text">
        Beyond coding, I have a keen interest in web security, Spring Security, and leveraging technology for social good. 
        My goal is to continuously learn and grow as a developer while contributing to meaningful projects.
      </p>
    </div>
</div>

<!-- Add TailwindCSS for animation -->
<style>
  .neon-btn {
    position: relative;
    overflow: hidden;
  }
  .neon-btn::before {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    width: 300%;
    height: 300%;
    background: rgba(255, 255, 255, 0.3);
    transition: all 0.5s;
    transform: translate(-50%, -50%) rotate(45deg);
    animation: neon-animation 2s infinite;
  }
  .neon-btn:hover::before {
    width: 0;
    height: 0;
  }
  
  @keyframes neon-animation {
    0% {
      transform: translate(-50%, -50%) rotate(45deg) scale(0.8);
      background: rgba(255, 255, 255, 0.3);
    }
    50% {
      transform: translate(-50%, -50%) rotate(45deg) scale(1);
      background: rgba(255, 255, 255, 0.5);
    }
    100% {
      transform: translate(-50%, -50%) rotate(45deg) scale(0.8);
      background: rgba(255, 255, 255, 0.3);
    }
  }

  /* Custom neon animation for text */
  .neon-animation-text {
    position: relative;
    display: inline-block;
    font-weight: bold;
    font-size: 1.125rem;
    color: #333;
    animation: neon-text 2s ease-in-out infinite alternate;
  }

  @keyframes neon-text {
    0% {
      text-shadow: 0 0 10px rgba(255, 255, 255, 0.8), 0 0 20px rgba(255, 255, 255, 0.6);
      color: #333;
    }
    50% {
      text-shadow: 0 0 20px rgba(255, 255, 255, 1), 0 0 30px rgba(255, 255, 255, 0.8);
      color: #000;
    }
    100% {
      text-shadow: 0 0 10px rgba(255, 255, 255, 0.8), 0 0 20px rgba(255, 255, 255, 0.6);
      color: #333;
    }
  }
</style>
