// src/app/projects/projects.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import AOS from 'aos'; 

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [ CommonModule ],
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.css']
})
export class ProjectsComponent implements OnInit {

  // AOS initialization in ngOnInit lifecycle hook
  ngOnInit() {
    AOS.init({
      duration: 1200, // Adjust duration as needed
      once: true      // Ensures animations happen only once
    });
  }

}

<div class="bg-gray-50 p-10 rounded-lg shadow-lg">
    <h2 class="text-3xl font-bold text-gray-800 text-center mb-8">Projects</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">

        <!-- Project 1 -->
        <div class="bg-white rounded-lg shadow-lg overflow-hidden transition-transform duration-300 hover:scale-105 project-card" data-aos="fade-up" data-aos-delay="100">
            <!-- Image Container -->
            <div class="h-48 overflow-hidden">
                <img alt="" class="w-full h-full object-cover zony" onerror="this.src='assets/images/placeholder.png'">
            </div>
            <!-- Content Container -->
            <div class="p-6">
                <h3 class="text-xl font-semibold text-gray-800 mb-2">ZONY Campus Smart LMS</h3>
                <p class="text-gray-600 mb-4 text-sm">A comprehensive campus management web application with intuitive interfaces and robust Java Spring Boot backend for streamlined educational and administrative workflows.</p>
                
                <!-- Technologies -->
                <div class="mb-4">
                    <div class="flex flex-wrap gap-2">
                        <span class="tech-tag">Spring Boot</span>
                        <span class="tech-tag">Angular</span>
                        <span class="tech-tag">MySQL</span>
                    </div>
                </div>
                
                <!-- Link -->
                <a href="https://github.com/Chathupachamika/Portfolio" target="_blank" class="neon-btn">
                    <i class="bi bi-arrow-right-circle-fill"></i> View Project
                </a>
            </div>
        </div>

        <!-- Project 2 -->
        <div class="bg-white rounded-lg shadow-lg overflow-hidden transition-transform duration-300 hover:scale-105 project-card" data-aos="fade-up" data-aos-delay="200">
            <!-- Image Container -->
            <div class="h-48 overflow-hidden">
                <img alt="" class="w-full h-full object-cover clothify" onerror="this.src='assets/images/placeholder.png'">
            </div>
            <!-- Content Container -->
            <div class="p-6">
                <h3 class="text-xl font-semibold text-gray-800 mb-2">Clothify Store</h3>
                <p class="text-gray-600 mb-4 text-sm">E-commerce platform built with modern technologies for seamless shopping experience.</p>
                
                <!-- Technologies -->
                <div class="mb-4">
                    <div class="flex flex-wrap gap-2">
                        <span class="tech-tag">Java FX</span>
                        <span class="tech-tag">MySQL</span>
                        <span class="tech-tag">Hibernate</span>
                    </div>
                </div>
                
                <!-- Link -->
                <a href="https://github.com/Chathupachamika/E-commerce" target="_blank" class="neon-btn">
                    <i class="bi bi-arrow-right-circle-fill"></i> View Project
                </a>
            </div>
        </div>

        <!-- Project 3 -->
        <div class="bg-white rounded-lg shadow-lg overflow-hidden transition-transform duration-300 hover:scale-105 project-card" data-aos="fade-up" data-aos-delay="300">
            <!-- Image Container -->
            <div class="h-48 overflow-hidden">
                <img alt="" class="w-full h-full object-cover weather" onerror="this.src='assets/images/placeholder.png'">
            </div>
            <!-- Content Container -->
            <div class="p-6">
                <h3 class="text-xl font-semibold text-gray-800 mb-2">Weather Application</h3>
                <p class="text-gray-600 mb-4 text-sm">Real-time weather application that allows users to view current weather conditions and forecasts for their location.</p>
                
                <!-- Technologies -->
                <div class="mb-4">
                    <div class="flex flex-wrap gap-2">
                        <span class="tech-tag">HTML</span>
                        <span class="tech-tag">CSS</span>
                        <span class="tech-tag">JavaScript</span>
                        <span class="tech-tag">Weather API</span>
                    </div>
                </div>
                
                <!-- Link -->
                <a href="https://github.com/Chathupachamika/weather-app" target="_blank" class="neon-btn">
                    <i class="bi bi-arrow-right-circle-fill"></i> View Project
                </a>
            </div>
        </div>

        <!-- Project 4 -->
        <div class="bg-white rounded-lg shadow-lg overflow-hidden transition-transform duration-300 hover:scale-105 project-card" data-aos="fade-up" data-aos-delay="400">
            <!-- Image Container -->
            <div class="h-48 overflow-hidden">
                <img alt="" class="w-full h-full object-cover burgers" onerror="this.src='assets/images/placeholder.png'">
            </div>
            <!-- Content Container -->
            <div class="p-6">
                <h3 class="text-xl font-semibold text-gray-800 mb-2">MOS Burgers</h3>
                <p class="text-gray-600 mb-4 text-sm">A standalone application featuring an intuitive user interface for efficient restaurant management.</p>
                
                <!-- Technologies -->
                <div class="mb-4">
                    <div class="flex flex-wrap gap-2">
                        <span class="tech-tag">JavaScript</span>
                        <span class="tech-tag">HTML</span>
                        <span class="tech-tag">CSS</span>
                    </div>
                </div>
                
                <!-- Link -->
                <a href="https://github.com/Chathupachamika/mos-burgers" target="_blank" class="neon-btn">
                    <i class="bi bi-arrow-right-circle-fill"></i> View Project
                </a>
            </div>
        </div>
        <div class="bg-white rounded-lg shadow-lg overflow-hidden transition-transform duration-300 hover:scale-105 project-card" data-aos="fade-up" data-aos-delay="500">
            <div class="h-48 overflow-hidden">
                <img alt="" class="w-full h-full object-cover defense" onerror="this.src='assets/images/placeholder.png'">
            </div>
            <div class="p-6">
                <h3 class="text-xl font-semibold text-gray-800 mb-2">Defense System</h3>
                <p class="text-gray-600 mb-4 text-sm">A strategic simulation application featuring components like submarines, tanks, and helicopters to model defense systems.</p>
                <div class="mb-4">
                    <div class="flex flex-wrap gap-2">
                        <span class="tech-tag">Java</span>
                        <span class="tech-tag">Observer Pattern</span>
                    </div>
                </div>
                <a href="https://github.com/Chathupachamika/Defense_System" target="_blank" class="neon-btn">
                    <i class="bi bi-arrow-right-circle-fill"></i> View Project
                </a>
            </div>
        </div>

        <!-- Another Project -->
        <div class="bg-white rounded-lg shadow-lg overflow-hidden transition-transform duration-300 hover:scale-105 project-card" data-aos="fade-up" data-aos-delay="600">
            <div class="h-48 overflow-hidden">
                <img alt="" class="w-full h-full object-cover todo" onerror="this.src='assets/images/placeholder.png'">
            </div>
            <div class="p-6">
                <h3 class="text-xl font-semibold text-gray-800 mb-2">Mahii's Tasks To Do</h3>
                <p class="text-gray-600 mb-4 text-sm">A JavaFX-based project showcasing GUI design and efficient task management.</p>
                <div class="mb-4">
                    <div class="flex flex-wrap gap-2">
                        <span class="tech-tag">JavaFX</span>
                        <span class="tech-tag">Java</span>
                    </div>
                </div>
                <a href="https://github.com/Chathupachamika/Mahii-s_tasks_javaFx" target="_blank" class="neon-btn">
                    <i class="bi bi-arrow-right-circle-fill"></i> View Project
                </a>
            </div>
        </div>
        <div class="bg-white rounded-lg shadow-lg overflow-hidden transition-transform duration-300 hover:scale-105 project-card" data-aos="fade-up" data-aos-delay="700">
            <!-- Image Container -->
            <div class="h-48 overflow-hidden">
                <img alt="" class="w-full h-full object-cover country" onerror="this.src='assets/images/placeholder.png'">
            </div>
            <!-- Content Container -->
            <div class="p-6">
                <h3 class="text-xl font-semibold text-gray-800 mb-2">Country Information Site</h3>
                <p class="text-gray-600 mb-4 text-sm">A web application displaying country-specific data such as population, language, and geography with a clean and responsive design.</p>
                
                <!-- Technologies -->
                <div class="mb-4">
                    <div class="flex flex-wrap gap-2">
                        <span class="tech-tag">HTML</span>
                        <span class="tech-tag">CSS</span>
                        <span class="tech-tag">JavaScript</span>
                    </div>
                </div>
                
                <!-- Link -->
                <a href="https://github.com/Chathupachamika/Country_Information_Site" target="_blank" class="neon-btn">
                    <i class="bi bi-arrow-right-circle-fill"></i> View Project
                </a>
            </div>
        </div>
        <div class="bg-white rounded-lg shadow-lg overflow-hidden transition-transform duration-300 hover:scale-105 project-card" data-aos="fade-up" data-aos-delay="800">
            <!-- Image Container -->
            <div class="h-48 overflow-hidden">
                <img alt="" class="w-full h-full object-cover wecare" onerror="this.src='assets/images/placeholder.png'">
            </div>
            <!-- Content Container -->
            <div class="p-6">
                <h3 class="text-xl font-semibold text-gray-800 mb-2">WeCare Prescription Management System</h3>
                <p class="text-gray-600 mb-4 text-sm">An innovative solution designed to streamline prescription processes, improve accuracy, and enhance healthcare delivery with robust security and advanced features.</p>
                
                <!-- Technologies -->
                <div class="mb-4">
                    <div class="flex flex-wrap gap-2">
                        <span class="tech-tag">Spring Boot</span>
                        <span class="tech-tag">Microservices</span>
                        <span class="tech-tag">Maven</span>
                        <span class="tech-tag">MySQL</span>
                        <span class="tech-tag">Angular</span>
                        <span class="tech-tag">TypeScript</span>
                    </div>
                </div>
                
                <!-- Link -->
                <a href="#" target="_blank" class="neon-btn">
                    <i class="bi bi-arrow-right-circle-fill"></i> View Project
                </a>
            </div>
        </div>
    </div>
</div>

// src/components/projects.jsx
"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { Card, CardContent, CardFooter } from "./ui/card"
import { Badge } from "./ui/badge"
import { Button } from "./ui/button"
import { ExternalLink, Github } from "lucide-react"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs"

export default function Projects() {
  const [hoveredIndex, setHoveredIndex] = useState(null)

  const projects = [
    {
      title: "ZONY Campus Smart LMS",
      description:
        "A comprehensive campus management web application with intuitive interfaces and robust Java Spring Boot backend for streamlined educational and administrative workflows.",
      image: "/project-images/zony.jpeg",
      link: "https://github.com/Chathupachamika/ZONY-Campus",
      technologies: ["Angular", "Java", "Spring Boot", "MySQL", "Rest API", "AI bot Gemini"],
      category: "fullstack",
    },
    {
      title: "Clothify Store",
      description: "E-commerce platform built with modern technologies for seamless shopping experience.",
      image: "/project-images/clothify.jpg",
      link: "https://github.com/Chathupachamika/Clothify_Store-app",
      technologies: ["JavaFX", "Java"],
      category: "desktop",
    },
    {
      title: "Weather Application",
      description:
        "Real-time weather application that allows users to view current weather conditions and forecasts for their location.",
      image: "/project-images/weather.jpg",
      link: "https://chathupachamika.github.io/Weather_site/",
      technologies: ["HTML", "CSS", "JavaScript", "API Handling"],
      category: "frontend",
    },
    {
      title: "Defense System",
      description:
        "A strategic simulation application featuring components like submarines, tanks, and helicopters to model defense systems.",
      image: "/project-images/defense.jpg",
      link: "https://github.com/Chathupachamika/Defense_System",
      technologies: ["Java", "Observer Pattern"],
      category: "desktop",
    },
    {
      title: "Mahii's Tasks To Do",
      description: "A JavaFX-based project showcasing GUI design and efficient task management.",
      image: "/project-images/todo.jpg",
      link: "https://github.com/Chathupachamika/Mahii-s_tasks_javaFx",
      technologies: ["JavaFX", "Java"],
      category: "desktop",
    },
    {
      title: "User Form Application",
      description:
        "A MERN stack user form is a full-stack application built with MongoDB, Express, React, and Node.js, enabling seamless user input, data storage, and dynamic UI updates.",
      image: "/project-images/userform.jpg",
      link: "https://github.com/Chathupachamika/User_Form-crud--MERN-Stack",
      technologies: ["React", "Node JS", "MongoDB", "Express JS"],
      category: "fullstack",
    },
    {
      title: "Country Information Site",
      description:
        "A web application displaying country-specific data such as population, language, and geography with a clean and responsive design.",
      image: "/project-images/country.jpg",
      link: "https://github.com/Chathupachamika/Country_Information_Site",
      technologies: ["HTML", "CSS", "JavaScript"],
      category: "frontend",
    },
    {
      title: "WeCare Prescription Management System",
      description:
        "An innovative solution designed to streamline prescription processes, improve accuracy, and enhance healthcare delivery with robust security and advanced features.",
      image: "/project-images/wecare.png",
      link: "https://github.com/iCET-110/Hospital-Management-Frontend",
      technologies: ["Spring Boot", "Microservices", "Maven", "MySQL", "Angular", "TypeScript"],
      category: "fullstack",
    },
    {
      title: "MOS Burgers",
      description:
        "A standalone application featuring an intuitive user interface for efficient restaurant management.",
      image: "/project-images/burgers.jpg",
      link: "https://chathupachamika.github.io/MOS_Burgers_project/",
      technologies: ["HTML", "CSS", "JavaScript", "RestAPI"],
      category: "frontend",
    },
  ]

  const categories = [
    { id: "all", name: "All Projects" },
    { id: "fullstack", name: "Full Stack" },
    { id: "frontend", name: "Frontend" },
    { id: "desktop", name: "Desktop Apps" },
  ]

  return (
    <section id="project" className="py-20 bg-gradient-to-b from-background/80 to-background">
      <div className="container px-4 md:px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="flex flex-col items-center text-center mb-12"
        >
          <Badge variant="outline" className="mb-4 px-4 py-1 text-sm border-primary/20">
            My Work
          </Badge>
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight mb-4">Featured Projects</h2>
          <div className="w-20 h-1 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full mb-8" />
          <p className="text-muted-foreground max-w-2xl">
            Here are some of the projects I've worked on. Each project represents different skills and technologies I've
            mastered.
          </p>
        </motion.div>

        <Tabs defaultValue="all" className="w-full max-w-6xl mx-auto">
          <TabsList className="grid grid-cols-2 md:grid-cols-4 mb-8">
            {categories.map((category) => (
              <TabsTrigger key={category.id} value={category.id}>
                {category.name}
              </TabsTrigger>
            ))}
          </TabsList>

          {categories.map((category) => (
            <TabsContent key={category.id} value={category.id} className="mt-4">
              <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {projects
                  .filter((project) => category.id === "all" || project.category === category.id)
                  .map((project, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, y: 20 }}
                      whileInView={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.5, delay: index * 0.1 }}
                      viewport={{ once: true }}
                      onMouseEnter={() => setHoveredIndex(index)}
                      onMouseLeave={() => setHoveredIndex(null)}
                      className="relative group"
                    >
                      <Card className="h-full overflow-hidden bg-card/50 backdrop-blur-sm border-primary/10">
                        <div className="relative h-48 overflow-hidden">
                          <img
                            src={project.image || "/placeholder.svg"}
                            alt={project.title}
                            className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                          />
                          <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end justify-start p-4">
                            <div className="flex gap-2">
                              <Button asChild size="sm" variant="default" className="gap-1">
                                <a href={project.link} target="_blank" rel="noopener noreferrer">
                                  <Github className="h-4 w-4" />
                                  Code
                                </a>
                              </Button>
                              {project.category === "frontend" && (
                                <Button asChild size="sm" variant="secondary" className="gap-1">
                                  <a href={project.link} target="_blank" rel="noopener noreferrer">
                                    <ExternalLink className="h-4 w-4" />
                                    Demo
                                  </a>
                                </Button>
                              )}
                            </div>
                          </div>
                        </div>
                        <CardContent className="p-4">
                          <h3 className="text-lg font-semibold mb-2">{project.title}</h3>
                          <p className="text-sm text-muted-foreground mb-4 line-clamp-3">{project.description}</p>
                        </CardContent>
                        <CardFooter className="p-4 pt-0 flex flex-wrap gap-2">
                          {project.technologies.slice(0, 3).map((tech, idx) => (
                            <Badge key={idx} variant="secondary" className="text-xs">
                              {tech}
                            </Badge>
                          ))}
                          {project.technologies.length > 3 && (
                            <Badge variant="outline" className="text-xs">
                              +{project.technologies.length - 3} more
                            </Badge>
                          )}
                        </CardFooter>
                      </Card>
                    </motion.div>
                  ))}
              </div>
            </TabsContent>
          ))}
        </Tabs>
      </div>
    </section>
  )
}
